Update Snyk to run with Java 11, which we now use
I missed this in https://github.com/guardian/media-atom-maker/pull/1149,
which upgraded media-atom-maker to use Java 11 - I didn't see that Snyk
was still configured to run under Java 8

When Snyk encountered the new Play 2.9 classes, which have been compiled
for Java 11 (Class File Version	55.0), it threw a `UnsupportedClassVersionError`,
and the sbt process was blocked, waiting for user input, hanging indefinitely:
(eventually I manually cancelled the GitHub job):

https://github.com/guardian/media-atom-maker/actions/runs/7899976195/job/21560525180#step:13:214
```
Error: -14T10:42:47.661Z snyk-sbt-plugin [error] java.lang.UnsupportedClassVersionError: play/api/PlayException$ExceptionSource has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Error: -14T10:42:47.661Z snyk-sbt-plugin [error] Use 'last' for the full log.
2024-02-14T10:42:47.665Z snyk-sbt-plugin [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
Error: The operation was canceled.
```

This should now be resolved, by the config update in this commit.