Bumping to Play 2.6.11
java.lang.NoClassDefFoundError on Play 2.6.0:

Caused by: java.lang.NoClassDefFoundError: play/api/libs/json/Json$MacroOptions$Default
	at com.gu.pandomainauth.service.GoogleAuth.discoveryDocument(GoogleAuth.scala:24)
	at com.gu.pandomainauth.service.GoogleAuth.redirectToGoogle(GoogleAuth.scala:57)
	at com.gu.pandomainauth.action.AuthActions$class.sendForAuth(Actions.scala:89)
	at MediaAtomMaker$$anon$1.sendForAuth(di.scala:57)
	at com.gu.pandomainauth.action.AuthActions$AuthAction$.invokeBlock(Actions.scala:246)
	at com.gu.pandomainauth.action.AuthActions$AuthAction$.invokeBlock(Actions.scala:228)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
	... 37 common frames omitted